services:
  db:
    image: mariadb:latest
    container_name: db-prato-solidario
    environment:
      MARIADB_ALLOW_EMPTY_PASSWORD: 1
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      MARIADB_ROOT_PASSWORD: "root"
      MARIADB_DATABASE: ${DATABASE_NAME:-prato_solidario}
      MARIADB_USER: ${DATABASE_USER:-user}
      MARIADB_PASSWORD: ${DATABASE_PASS:-pass}
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 5s
      interval: 2s
      timeout: 5s
      retries: 5
    ports:
      - ${DATABASE_PORT:-3306}:3306
    restart: always
  app:
    build: .
    tty: true
    container_name: app-prato-solidario
    working_dir: /app
    volumes:
      - .:/app
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
