# Generated by Django 5.1.1 on 2024-09-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('image_path', models.ImageField(default='static/img/default/campaign-thumbnail.jpg', upload_to='uploads/')),
                ('how_help', models.TextField(max_length=500)),
                ('votes', models.IntegerField(default=0)),
                ('limit_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'campaigns',
            },
        ),
    ]
