name: Docker Compose Action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker Compose Action
      uses: hoverkraft-tech/compose-action@v2.0.2
      with:
        compose-file: "docker-compose.yml"
    - name: Run migrations
      run: docker-compose exec -T app-prato-solidario python manage.py migrate
    - name: Start server
      run: docker-compose exec -T app-prato-solidario python manage.py runserver 0.0.0.0:8000
